# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_plaid
# 
# Translators:
# zbik2607 <darek@krokus.com.pl>, 2016
# Piotr Szlązak <szlazakpiotr@gmail.com>, 2016
msgid ""
msgstr ""
"Project-Id-Version: Odoo 9.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-10-01 06:30+0000\n"
"PO-Revision-Date: 2016-10-06 09:08+0000\n"
"Last-Translator: zbik2607 <darek@krokus.com.pl>\n"
"Language-Team: Polish (http://www.transifex.com/odoo/odoo-9/language/pl/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: pl\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_token
msgid "Access Token"
msgstr "Token dostępu"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:52
#: code:addons/account_plaid/models/plaid.py:63
#, python-format
msgid "An error has occurred while trying to connect to plaid service"
msgstr "Wystąpił błąd podczas próby połączenia się do serwisu Plaid"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_account
msgid "Email Thread"
msgstr "Wątek email"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:129
#, python-format
msgid "Error in synchronization"
msgstr "Błąd w synchronizacji"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:136
#, python-format
msgid "Error with Plaid.com"
msgstr "Błąd Plaid.com"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal
msgid "Journal"
msgstr "Dziennik"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_journal_onlinesync_config_plaid_account_id
msgid "Online Account"
msgstr "Konto online"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_plaid_id
msgid "Plaid Account"
msgstr "konto pledu"

#. module: account_plaid
#: model:ir.ui.view,arch_db:account_plaid.account_config_settings_view_inherit_plaid
msgid "Plaid Configuration"
msgstr "konfiguracje pled"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_id
msgid "Plaid ID"
msgstr ""

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_secret
msgid "Plaid Secret"
msgstr "Plaid sekret"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:130
#, python-format
msgid ""
"The synchronization of the journal %s with the plaid account %s has "
"failed.<br>The error message is :<br>%s"
msgstr ""

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:137
#, python-format
msgid ""
"The synchronization with Plaid.com failed. Please check the error : <br> %s"
msgstr ""

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:38
#, python-format
msgid ""
"You haven't configure your plaid account, please go to accounting/settings "
"to configure it"
msgstr ""

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_config_settings
msgid "account.config.settings"
msgstr "account.config.settings"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal_onlinesync_config
msgid "account.journal.onlinesync.config"
msgstr "account.journal.onlinesync.config"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_institution
msgid "online.institution"
msgstr "instytucja.online"
